Repository DNNCommunity/Dnn.CommunityMetrics, pull requests merged in 2024-02, with the labels that each got.

#52 Add links to issues and pull requests in detail view
  Components/GitHubIssueActivity.cs
  Components/GitHubPullRequestActivity.cs
  Controllers/UserActivityController.cs
  DAL/CommunityMetrics.dbml
  DAL/CommunityMetrics.dbml.layout
  DAL/CommunityMetrics.designer.cs
  DTOs/UserActivityDTO.cs
  Dnn.CommunityMetrics.csproj
  Dnn.CommunityMetrics.dnn
  Module.css
  Properties/AssemblyInfo.cs
  SchedulerJobs/ActivityJob.cs
  Scripts/01.03.00.sql
  app/views/user-activity/user-activity-detail2.html
Labels: enhancement

#53 Merge `main` into `develop` to try and resolve gitversion issues
  app/controllers/user-activity/user-activity-list.js
Labels: bug

#54 Update version in manifest
  Dnn.CommunityMetrics.dnn
  build/_build.csproj
Labels: maintenance

#55 Merge `release/1.3.0` into `main` for `1.3.0` release
  Components/GitHubIssueActivity.cs
  Components/GitHubPullRequestActivity.cs
  Controllers/UserActivityController.cs
  DAL/CommunityMetrics.dbml
  DAL/CommunityMetrics.dbml.layout
  DAL/CommunityMetrics.designer.cs
  DTOs/UserActivityDTO.cs
  Dnn.CommunityMetrics.csproj
  Dnn.CommunityMetrics.dnn
  Module.css
  Properties/AssemblyInfo.cs
  SchedulerJobs/ActivityJob.cs
  Scripts/01.03.00.sql
  app/controllers/user-activity/user-activity-list.js
  app/views/dashboard.html
  app/views/user-activity/user-activity-detail2.html
  app/views/user-activity/user-activity-edit.html
  app/views/user-activity/user-activity-list.html
  build/_build.csproj
Labels: build/release

#56 Attempt to resolve build issues
  .nuke/build.schema.json
  build/Build.cs
Labels: build/release

#57 Remove checksums
  build/Build.cs
Labels: bug

#58 Merged `release/1.3.0` into `main` for `1.3.0` release
  .nuke/build.schema.json
  build/Build.cs
Labels: build/release

#59 Change compatibility for SQL script 01.03.00
  Scripts/01.03.00.sql
Labels: bug

#60 Merge `release/1.3.0` into `main` for `1.3.0` release
  Scripts/01.03.00.sql
Labels: build/release

#61 Fixed a typo in the avatar URL
  app/views/dashboard.html
Labels: bug

#62 Merged `release/1.3.1` into `main` for `1.3.1` release
  app/views/dashboard.html
Labels: build/release
